Re-Input/reinput-auth-service

.gitignore, build.gradle, src/main/java/info/reinput/global/config/WebMvcConfig.java, src/main/java/info/reinput/global/domain/TokenType.java, src/main/java/info/reinput/global/domain/application/PrincipalDetailsService.java, src/main/java/info/reinput/global/domain/auth/PrincipalDetails.java, src/main/java/info/reinput/global/util/AuthorityUtils.java, src/main/java/info/reinput/global/util/JwtAuthenticationInterceptor.java, src/main/java/info/reinput/global/util/TokenProvider.java, src/main/java/info/reinput/member/application/MemberService.java, src/main/java/info/reinput/member/domain/Member.java, src/main/java/info/reinput/member/domain/MemberAuth.java, src/main/java/info/reinput/member/domain/MemberEmail.java, src/main/java/info/reinput/member/domain/MemberInfo.java, src/main/java/info/reinput/member/domain/MemberRole.java, src/main/java/info/reinput/member/domain/dto/req/SignUpReq.java, src/main/java/info/reinput/member/infra/MemberRespository.java, src/main/java/info/reinput/member/infra/impl/CustomMemberRepositoryImpl.java, src/main/java/info/reinput/member/presentation/MemberController.java, src/main/resources/application.yml
PrincipalDetails, Service
AuthService(TokenProvider)
JwtInterceptor구현
- close #98
- [Jira-ticket] Member Auth 구현
=> Feat/member Auth 구현

build.gradle, src/main/java/info/reinput/global/config/FeignConfig.java, src/main/resources/application.yml
---
labels: 
assignees: ''
---
- RE-166
=> RE-166 chore: feign 의존성 추가 및 configuration 설정

src/main/java/info/reinput/member/application/dto/FolderCreateReq.java, src/main/java/info/reinput/member/application/impl/MemberServiceImpl.java, src/main/java/info/reinput/member/application/port/out/WorkspacePort.java, src/main/java/info/reinput/member/infra/client/WorkspaceClient.java, src/main/java/info/reinput/member/infra/client/WorkspaceFeignAdapter.java
---
labels: 
assignees: ''
---
- RE-130
=> RE-153 feat: workspace service topic folder create 기능 구현

build.gradle, src/main/java/info/reinput/global/config/SecurityConfig.java, src/main/java/info/reinput/global/config/SwaggerConfig.java, src/main/java/info/reinput/member/presentation/MemberController.java
---
name: Swagger 설정
about: Swagger 설정 및 보안 허용
title: "[feat]"
labels: 
assignees: 'Jhsysng'
---
- swagger 종속성 버전 변경
- swagger config 
- swagger jwt
- swagger oauth
- security config 설정 추가
- RE-167 auth service swagger setting
=> Re 167 auth service swagger setting

src/main/java/info/reinput/global/config/SwaggerConfig.java
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger base url /member 변경

src/main/java/info/reinput/global/config/SwaggerConfig.java, src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger 설정

src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger 설정 config base url 추가

src/main/java/info/reinput/global/config/SwaggerConfig.java
---
labels: 
assignees: ''
---
=> RE-167 swagger kakao 설정 추가

src/main/java/info/reinput/global/config/SwaggerConfig.java
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger kakao 기능 id, pw로 변경

src/main/java/info/reinput/global/config/SwaggerConfig.java
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger kakao 자동주입

src/main/java/info/reinput/global/config/SwaggerConfig.java
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger kakao 자동주입 Map 방식 변경

src/main/java/info/reinput/global/config/SwaggerConfig.java, src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 feat: swagger kakao 자동주입 yml 방식 변경

src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 임시 url 지정

src/main/java/info/reinput/global/config/SwaggerConfig.java, src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 임시 url 수정

src/main/java/info/reinput/global/config/SwaggerConfig.java
---
labels: 
assignees: ''
---
=> RE-167 feat: x-user-id 무시 설정

src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 eureka server 설정 변경

src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 server headers strategy 설정 변경

src/main/java/info/reinput/member/infra/OAuth2AuthenticationSuccessHandler.java
---
labels: 
assignees: ''
---
=> RE-167 Success handler 수정 200 OK 추가

src/main/java/info/reinput/global/config/SecurityConfig.java, src/main/java/info/reinput/member/infra/OAuth2AuthenticationSuccessHandler.java
---
labels: 
assignees: ''
---
=> RE-167 Session Saved Request 방지

src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 security debug log 활성화

src/main/java/info/reinput/global/config/SecurityConfig.java
---
labels: 
assignees: ''
---
=> RE-167 stateless 설정 삭제

src/main/resources/application.yml
---
labels: 
assignees: ''
---
=> RE-167 swagger oauth2 redirect url 수정

.gitignore, Dockerfile, src/main/resources/application-dev.properties.example, src/main/resources/application-dev.yml, src/main/resources/application-local.properties.example, src/main/resources/application-local.yml, src/main/resources/application.yml
- Modified .gitignore to include all application property files.
- Updated Dockerfile to set the active Spring profile to 'dev'.
- Enhanced application-dev.properties.example with database and JWT configurations.
- Added application-dev.yml for the development profile with complete datasource and security settings.
- Created application-local.properties.example and application-local.yml for local development setup.
- Changed the default active profile in application.yml from 'dev' to 'local' to reflect local development settings.
---
labels: 
assignees: ''
---
- [RE-170]
[RE-170]: https://reinput.atlassian.net/browse/RE-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RE-170] Update application configuration for development and local environments

src/main/java/info/reinput/member/presentation/MemberController.java
---
title: "feat: X-User-Id Swagger 비활성화"
labels: 
assignees: Jhsysng
---
- RE-167
=> RE-167 X-User-Id 비활성화

.github/workflows/cd.yml, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application.yml
- Added SERVICE_NAME environment variable to cd.yml
- Updated docker commands to use dynamic service name
- Simplified deployment script by replacing hardcoded service name with variable
- [RE-173]
[RE-173]: https://reinput.atlassian.net/browse/RE-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RE-173 Refactor CD workflow to use dynamic service name variable
